apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalability-demo-deployment
  labels:
    app.kubernetes.io/name: "scalability-demo"
    logging.free.text.enabled: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/metrics"
    prometheus.io/port: "8080"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: "scalability-demo"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "scalability-demo"
    spec:
      containers:
        - name: scalability-demo
          image:  nikolahristovski/springboot-scalability:1.0.0
          ports:
            - containerPort: 8080