apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: scalability-demo-http-scaler
  labels:
    deploymentName: frontend
spec:
  host: "scalabilitydemo.example.com"
  scaleTargetRef:
    name: scalability-demo-deployment
    service: scalability-demo-node-port
    port: 30001
  targetPendingRequests: 5
  replicas:
    min: 0
    max: 2