apiVersion: v1
kind: Service
metadata:
  name: scalability-demo-node-port
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "scalability-demo"
