apiVersion: v1
kind: Service
metadata:
  name: scalability-demo-node-port
  labels:
    app.kubernetes.io/name: "scalability-demo"
spec:
  type: NodePort
  ports:
    - port: 30001
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "scalability-demo"
