apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scalability-demo
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: apps
    repoURL: 'https://github.com/NHristovski/argocd-app-of-apps/'
    targetRevision: HEAD
  project: default
