apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istio-base
      targetRevision: 1.24.2
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.24.2
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istio-ingressgateway
      targetRevision: 1.24.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

