apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: 2.16.0
    - repoURL: https://kedacore.github.io/charts
      chart: keda-add-ons-http
      targetRevision: 0.9.0
      helm:
        values: |
          interceptor:
            tcpConnectTimeout: 25s
            responseHeaderTimeout: 25s
            expectContinueTimeout: 25s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

