apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.15.0
      helm:
        values: |
          loki:
            commonConfig:
              replication_factor: 1
            storage:
              type: "filesystem"
              filesystem:
                chunks_directory: "/var/loki/chunks"
                rules_directory: "/var/loki/rules"

            rulerConfig:
              storage:
                type: local

          singleBinary:
            replicas: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
