apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: prometheus
      targetRevision: "26.0.1"
      helm:
        values: |
          prometheus-pushgateway:
            enabled: false
          prometheus-node-exporter:
            enabled: false
          kube-state-metrics:
            enabled: false
          alertmanager:
            enabled: false
          extraScrapeConfigs: |
            - job_name: 'kubernetes-service-endpoints-scrape-every-5s'

              scrape_interval: 5s

              kubernetes_sd_configs:
                - role: pod

              relabel_configs:
                #Custom
                - source_labels: [__meta_kubernetes_service_annotation_example_com_scrape_every_5s]
                  action: keep
                  regex: true

                # Boilerplate
                - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
                  action: replace
                  target_label: __scheme__
                  regex: (https?)
                - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
                  action: replace
                  target_label: __address__
                  regex: ([^:]+)(?::\d+)?;(\d+)
                  replacement: $1:$2
                - action: labelmap
                  regex: __meta_kubernetes_service_label_(.+)
                - source_labels: [__meta_kubernetes_namespace]
                  action: replace
                  target_label: kubernetes_namespace
                - source_labels: [__meta_kubernetes_service_name]
                  action: replace
                  target_label: kubernetes_name
                - source_labels: [__meta_kubernetes_pod_node_name]
                  action: replace
                  target_label: kubernetes_node
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
