apiVersion: v1
kind: ConfigMap
metadata:
  name: client-script-config-map
data:
  script.sh: |
    for i in {0..150}
    do
      curl --header "Host: scalabilitydemo.example.com" keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local:8080/threeSecondsRequest &
    done

