apiVersion: v1
kind: ConfigMap
metadata:
  name: client-knative-script-config-map
data:
  script.sh: |
    for i in {0..150}
    do
      curl http://scalability-demo-knative.project.svc.cluster.local/threeSecondsRequest &
    done
