apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: scalability-demo-knative
  namespace: project
spec:
  template:
    metadata:
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: nikolahristovski/springboot-scalability:1.0.0